=== wixiw/Atlantronic/arp_ihm/src/www/ressource/bom/Parts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by dus (dus) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="version" type="xs:string"/>
					
				<xs:element name="parts">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="part" type="part" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="part">
		<xs:sequence>
			<xs:element name="code" type="xs:string"/>
			<xs:element name="revision" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="picturefile" type="xs:string"/>
			<xs:element name="definition_documents">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="document" type="document" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="comments" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="article">
		<xs:complexContent>
			<xs:extension base="part">
				<xs:sequence>
					<xs:element name="price" type="xs:decimal" minOccurs="0"/>
					<xs:element name="supplier_name" type="xs:string" minOccurs="0"/>
					<xs:element name="supplier_ref" type="xs:string" minOccurs="0"/>
					<xs:element name="hyperlink" type="xs:anyURI" minOccurs="0"/>
					<xs:element name="supplier_documents" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="document" type="document" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="assembly">
		<xs:complexContent>
			<xs:extension base="part">
				<xs:sequence>
					<xs:element name="is_composed_of">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="instance" type="instance" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="instance">
		<xs:sequence>
			<xs:element name="code" type="xs:string"/>
			<xs:element name="revision" type="xs:string"/>
			<xs:element name="quantity" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="document">
		<xs:sequence>
			<xs:element name="filename" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="collection">
		<xs:complexContent>
			<xs:extension base="part">
				<xs:sequence>
					<xs:element name="is_composed_of">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="instance" type="instance" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== wixiw/Atlantronic/arp_ihm/src/www/ressource/bom/Parts.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by dus (dus) -->
<root xsi:noNamespaceSchemaLocation="Parts.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<version>3.0</version>
	<parts>
		<part xsi:type="assembly">
			<code>Q004</code>
			<revision>B</revision>
			<name>tourelle</name>
			<picturefile>files/Q004/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/Q004/Q004_B tourelle sur support.3dxml</filename>
					<name>3dxml file</name>
				</document>
				<document>
					<filename>files/Q004/Q004_B tourelle sur support.pdf</filename>
					<name>drawing</name>
				</document>
				<document>
					<filename>files/Q004/Q004_B tourelle sur support.zip</filename>
					<name>3D STEP file</name>
				</document>
			</definition_documents>
			<comments/>
			<is_composed_of>
				<instance>
					<code>A001</code>
					<revision>C</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>V004</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>S002</code>
					<revision>A</revision>
					<quantity>4</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="assembly">
			<code>B001</code>
			<revision>A</revision>
			<name>Roulement pivot equipe</name>
			<picturefile>files/B001/picture.jpg</picturefile>
			<definition_documents/>
			<comments>Coller la bague Ã  l'interieur du roulement</comments>
			<is_composed_of>
				<instance>
					<code>C001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>D001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="assembly">
			<code>E001</code>
			<revision>A</revision>
			<name>Roue dentee PG1.25-70 modifiee</name>
			<picturefile>files/E001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/E001/E001_A roue dentee PG1.25-70 modifiee.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments>Reprise d'usinage sur un engrenage standard</comments>
			<is_composed_of>
				<instance>
					<code>B005</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="assembly">
			<code>E001</code>
			<revision>C</revision>
			<name>Roue dentee G1.25-70 modifiee</name>
			<picturefile>files/E001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/E001/E001_C roue dentee G1.25-70 modifiee.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments>Reprise d'usinage sur un engrenage standard</comments>
			<is_composed_of>
				<instance>
					<code>B005</code>
					<revision>B</revision>
					<quantity>1</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="article">
			<code>B005</code>
			<revision>B</revision>
			<name>Roue dentee G1.25-70</name>
			<picturefile>files/B005/picture.jpg</picturefile>
			<definition_documents/>
			<comments/>
			<price>47.81</price>
			<supplier_name>HPC Engrenages</supplier_name>
			<supplier_ref>G1.25-70</supplier_ref>
			<hyperlink></hyperlink>
			<supplier_documents>
				<document>
					<filename>files/Common/G1.25.pdf</filename>
					<name>brochure spur gear</name>
				</document>
			</supplier_documents>
		</part>
		<part xsi:type="article">
			<code>C001</code>
			<revision>A</revision>
			<name>roulement q61810zz</name>
			<picturefile>files/C001/picture.jpg</picturefile>
			<definition_documents/>
			<comments/>
			<price>78.39</price>
			<supplier_name>HPC Engrenages</supplier_name>
			<supplier_ref>q61810zz</supplier_ref>
			<hyperlink></hyperlink>
			<supplier_documents>
				<document>
					<filename>files/C001/Q6.pdf</filename>
					<name>brochure radial bearing</name>
				</document>
			</supplier_documents>
		</part>
		<part xsi:type="article">
			<code>D001</code>
			<revision>A</revision>
			<name>bague int roulement</name>
			<picturefile>files/D001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/D001/D001_A bague int roulement.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments/>
			<price>0</price>
			<supplier_name/>
			<supplier_ref/>
			<hyperlink/>
			<supplier_documents/>
		</part>
		<part xsi:type="assembly">
			<code>I001</code>
			<revision>C</revision>
			<name>Corps tourelle et pivot</name>
			<picturefile>files/I001/picture.jpg</picturefile>
			<definition_documents/>
			<comments>
				Coller les goupilles dans la roue dentee. visser la roue dentee sur le corps
					tourelle. Coller le roulement equipe sur le corps tourelle equipe
			</comments>
			<is_composed_of>
				<instance>
					<code>S005</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>B001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>E001</code>
					<revision>C</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>U005</code>
					<revision>A</revision>
					<quantity>4</quantity>
				</instance>
				<instance>
					<code>G001</code>
					<revision>B</revision>
					<quantity>3</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="article">
			<code>H001</code>
			<revision>A</revision>
			<name>vis tete fraisee M3x10</name>
			<picturefile>files/H001/picture.jpg</picturefile>
			<definition_documents/>
			<comments/>
			<price>0.05</price>
			<supplier_name/>
			<supplier_ref/>
			<hyperlink/>
			<supplier_documents/>
		</part>
		<part xsi:type="article">
			<code>G001</code>
			<revision>B</revision>
			<name>goupillediam 3</name>
			<picturefile>files/G001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/G001/G001_B goupille diam 3.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments/>
			<price>0</price>
			<supplier_name/>
			<supplier_ref/>
			<hyperlink/>
			<supplier_documents/>
		</part>
		<part xsi:type="article">
			<code>S005</code>
			<revision>A</revision>
			<name>corps tourelle</name>
			<picturefile>files/S005/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/S005/S005_A corps tourelle fraise.pdf</filename>
					<name>drawing</name>
				</document>
				<document>
					<filename>files/S005/S005_A corps tourelle fraise.stp</filename>
					<name>3D file</name>
				</document>
			</definition_documents>
			<comments/>
			<price>0</price>
			<supplier_name/>
			<supplier_ref/>
			<hyperlink/>
			<supplier_documents/>
		</part>
		<part xsi:type="assembly">
			<code>J001</code>
			<revision>C</revision>
			<name>Partie tournante tourelle sans roue</name>
			<picturefile>files/J001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/J001/J001_C partie tournante tourelle sans roue.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments/>
			<is_composed_of>
				<instance>
					<code>I001</code>
					<revision>C</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>K001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>L001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>M001</code>
					<revision>B</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>N001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>O001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>P001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>Q001</code>
					<revision>B</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>R001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>Z001</code>
					<revision>A</revision>
					<quantity>1</quantity>
				</instance>
				<instance>
					<code>T001</code>
					<revision>B</revision>
					<quantity>1</quantity>
				</instance>
			</is_composed_of>
		</part>
		<part xsi:type="article">
			<code>K001</code>
			<revision>A</revision>
			<name>roulement colerette sf980zz</name>
			<picturefile>files/K001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/K001/K001_A roulement colerette sf980zz.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments/>
			<price>28.31</price>
			<supplier_name>HPC Engrenages</supplier_name>
			<supplier_ref>SF980ZZ</supplier_ref>
			<hyperlink></hyperlink>
			<supplier_documents>
				<document>
					<filename>files/K001/SF_ZZ.pdf</filename>
					<name>brochure radial bearing</name>
				</document>
			</supplier_documents>
		</part>
		<part xsi:type="article">
			<code>L001</code>
			<revision>A</revision>
			<name>roulement colerette F6801ZZ</name>
			<picturefile>files/L001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/L001/L001_A roulement colerette F6801.pdf</filename>
					<name>drawing</name>
				</document>
			</definition_documents>
			<comments/>
			<price>8</price>
			<supplier_name>1001 Roulements</supplier_name>
			<supplier_ref>F6801ZZ</supplier_ref>
			<hyperlink></hyperlink>
			<supplier_documents/>
		</part>
		<part xsi:type="article">
			<code>M001</code>
			<revision>B</revision>
			<name>axe roue</name>
			<picturefile>files/M001/picture.jpg</picturefile>
			<definition_documents>
				<document>
					<filename>files/M001/M001_B axe roue.pdf</filename>
